default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: furima_39925_development

test:
  <<: *default
  database: furima_39925_test

production:
  <<: *default
  database: furima_39925_production
  username: furima_39925
  password: <%= ENV["FURIMA_39925_DATABASE_PASSWORD"] %>
